In [68]:
import pandas as pd
import numpy as np
import re

In [74]:
df = pd.read_csv("/Users/momo/Dropbox/Stanford/whquestions-tgrep2/experiments/01_experiment/01_pilot/results/rscripts/df_nested.csv").drop(columns="Unnamed: 0")

In [29]:
df.head()

,workerid,proliferate.condition,order,response,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,subject_information.comments,...,DeterminerNonSubject,FullWhPhrase,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ
0,38,condition1,NaN,"['Mary', 'Mary']",1,bot_check,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,38,condition1,a-the-all-some,"['all', False]",3,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,38,condition1,a-the-all-some,"['a', False]",4,example2,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38,condition1,a-the-all-some,"['all', False]",5,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,38,condition1,a-the-all-some,"['the', False]",6,example4,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_split = df.response.apply(pd.Series).merge(df, left_index = True, right_index = True)

In [24]:
df_split.head()

,0,workerid,proliferate.condition,order,response,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,...,DeterminerNonSubject,FullWhPhrase,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ
0,"['Mary', 'Mary']",38,condition1,NaN,"['Mary', 'Mary']",1,bot_check,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"['all', False]",38,condition1,a-the-all-some,"['all', False]",3,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"['a', False]",38,condition1,a-the-all-some,"['a', False]",4,example2,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"['all', False]",38,condition1,a-the-all-some,"['all', False]",5,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"['the', False]",38,condition1,a-the-all-some,"['the', False]",6,example4,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df[['response','strange']] = pd.DataFrame(df.response.tolist(), index= df.index)

ValueError: Columns must be same length as key

In [28]:
pd.DataFrame(df["response"].to_list(), columns=['response', 'strange'])

ValueError: Shape of passed values is (562, 1), indices imply (562, 2)

In [33]:
df2 = df.response.apply(pd.Series)
# df2.columns = ['response', 'strange']

In [54]:
df2.head()

                  0
0  ['Mary', 'Mary']
1    ['all', False]
2      ['a', False]
3    ['all', False]
4    ['the', False]

In [57]:
df.response.dtype

dtype('O')

In [75]:
df.response = df.response.apply(lambda x: re.sub(r'[^\w\s]','',x))

In [78]:
df.head()

,workerid,proliferate.condition,order,response,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,subject_information.comments,...,DeterminerNonSubject,FullWhPhrase,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ
0,38,condition1,NaN,Mary Mary,1,bot_check,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,38,condition1,a-the-all-some,all False,3,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,38,condition1,a-the-all-some,a False,4,example2,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38,condition1,a-the-all-some,all False,5,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,38,condition1,a-the-all-some,the False,6,example4,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
df_res = pd.DataFrame(df.response.str.split(' ',1).tolist(), columns = ['response','is_strange'])

In [91]:
total = df_res.merge(df, left_index = True, right_index = True).drop(columns="response_y").rename(columns={"response_x": "response"})

In [92]:
total.head()

,response,is_strange,workerid,proliferate.condition,order,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,...,DeterminerNonSubject,FullWhPhrase,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ
0,Mary,Mary,38,condition1,NaN,1,bot_check,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,all,False,38,condition1,a-the-all-some,3,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,a,False,38,condition1,a-the-all-some,4,example2,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,all,False,38,condition1,a-the-all-some,5,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,the,False,38,condition1,a-the-all-some,6,example4,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
total.to_csv("total_unnested.csv",header=True)

In [77]:
df[["response","strange"]] = df.response.str.split(" ",expand=True)

ValueError: Columns must be same length as key

In [53]:
# df.response.apply(pd.Series).merge(df, left_index = True, right_index = True)

,0,workerid,proliferate.condition,order,response,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,...,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ,response1,response2
0,"['Mary', 'Mary']",38,condition1,NaN,"['Mary', 'Mary']",1,bot_check,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Mary', 'Mary']","['Mary', 'Mary']"
1,"['all', False]",38,condition1,a-the-all-some,"['all', False]",3,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['all', False]","['all', False]"
2,"['a', False]",38,condition1,a-the-all-some,"['a', False]",4,example2,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['a', False]","['a', False]"
3,"['all', False]",38,condition1,a-the-all-some,"['all', False]",5,example1,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['all', False]","['all', False]"
4,"['the', False]",38,condition1,a-the-all-some,"['the', False]",6,example4,[],41.0,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['the', False]","['the', False]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,"['some', False]",36,condition1,the-some-a-all,"['some', False]",13,40349:14,[],49.0,Yes,...,no,no,NaN,(WRB how),"you know, how can you help *-1 depending on th...",(TOP (SBARQ (PRN (S (NP-SBJ (PRP You)) (VP (VB...,monomorphemic,no,"['some', False]","['some', False]"
558,"['the', False]",36,condition1,the-some-a-all,"['the', False]",14,60430:4,[],49.0,Yes,...,no,NaN,NaN,(WP who),who *t*-1 knows.,(TOP (SBARQ (WHNP-1 (WP who)) (SQ (NP-SBJ (-NO...,monomorphemic,no,"['the', False]","['the', False]"
559,"['a', False]",36,condition1,the-some-a-all,"['a', False]",15,37508:7,[],49.0,Yes,...,no,no,NaN,(WRB how),well how do you think 0 the royals are going *...,(TOP (SBARQ (INTJ (UH well)) (WHADVP-2 (WRB ho...,monomorphemic,no,"['a', False]","['a', False]"
560,"['some', False]",36,condition1,the-some-a-all,"['some', False]",16,102105:4,[],49.0,Yes,...,no,yes,NaN,(WRB How),"how do you usually find a, a new restaurant *t...",(TOP (SBARQ (WHADVP-1 (WRB How)) (SQ (VBP do) ...,monomorphemic,no,"['some', False]","['some', False]"
561,"['a', False]",36,condition1,the-some-a-all,"['a', False]",17,130644:22,[],49.0,Yes,...,no,NaN,NaN,(WRB where),"oh, g-, where *ich*-3 have i gone *t*-1 that *...","(TOP (SBARQ (INTJ (UH Oh)) (, ,) (EDITED (RM (...",monomorphemic,no,"['a', False]","['a', False]"

In [35]:
for i in [0,1]:
    df['response{}'.format(str(i+1))]=[k[i] if isinstance(k,list) else k for k in df['response']]

In [36]:
df.head()

,workerid,proliferate.condition,order,response,slide_number_in_experiment,tgrep_id,catch_trials,subject_information.age,subject_information.asses,subject_information.comments,...,DeterminerSubjPresent,DeterminerNonSubjPresent,WhNode,WhParse,Question,SentenceParse,WhPhaseType,IdentityQ,response1,response2
0,38,condition1,NaN,"['Mary', 'Mary']",1,bot_check,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['Mary', 'Mary']","['Mary', 'Mary']"
1,38,condition1,a-the-all-some,"['all', False]",3,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['all', False]","['all', False]"
2,38,condition1,a-the-all-some,"['a', False]",4,example2,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['a', False]","['a', False]"
3,38,condition1,a-the-all-some,"['all', False]",5,example1,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['all', False]","['all', False]"
4,38,condition1,a-the-all-some,"['the', False]",6,example4,[],41.0,Yes,"If I checked ""none of the above"" I was still f...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['the', False]","['the', False]"